// swift-tools-version: 5.10
// The swift-tools-version declares the minimum version of Swift required to build this package.

import PackageDescription

let package = Package(
    name: "LakeKit",
    platforms: [.macOS(.v13), .iOS(.v15)],
    products: [
        // Products define the executables and libraries a package produces, and make them visible to other packages.
        .library(
            name: "LakeKit",
//            type: .dynamic,
            targets: ["LakeKit"]),
    ],
    dependencies: [
//        .package(url: "https://github.com/lake-of-fire/RealmBinary.git", branch: "main"),
        .package(url: "https://github.com/realm/realm-swift.git", from: "20.0.3"),
        .package(url: "https://github.com/lake-of-fire/BigSyncKit.git", revision: "cc8fe4ae9346f568cb9a337a670a5a5712ad2735"),
        .package(url: "https://github.com/lake-of-fire/RealmSwiftGaps.git", revision: "f2f5e54628b3474f281ae3d70fc3aaed471a9ecd"),
        .package(url: "https://github.com/lake-of-fire/SwiftUIDownloads.git", revision: "03706f88e149d0e07e9a27ade6da8a8985a5ca9f"),
        .package(url: "https://github.com/lake-of-fire/SwiftUtilities.git", revision: "15f8313b36c066dedffd662809b52de965efa6b6"),
        .package(url: "https://github.com/lake-of-fire/LakeImage.git", revision: "beb6dc915860cef92db6ea9e3c6bfef494c8b707"),
//        .package(url: "https://github.com/NuPlay/ExpandableText.git", branch: "main"),
        .package(url: "https://github.com/lake-of-fire/swiftui-webview.git", revision: "63672ef88b16900ce1063276d3dca15ad0ca3064"),
//        .package(url: "https://github.com/demharusnam/SwiftUIDrag.git", branch: "main"),
        .package(url: "https://github.com/lake-of-fire/Popovers.git", revision: "13b52ae6bf053878fd8b59e79aaaa75cd9f6147a"),
        .package(url: "https://github.com/apple/swift-collections.git", revision: "6741fb960b770d26e416a472e32c23077ed181e7"),
        .package(url: "https://github.com/lake-of-fire/BetterSafariView2.git", revision: "4e0f3af7787296e73e6b68499f7d78441b798649"),
        .package(url: "https://github.com/lake-of-fire/keychain-swift.git", branch: "master"),
        .package(url: "https://github.com/lake-of-fire/DSFSearchField.git", revision: "2b8fe511d76a6aeb46afa2242d18b6cd9f7455d1"),
//        .package(url: "https://github.com/twostraws/Inferno.git", branch: "main"),
//        .package(url: "https://github.com/elai950/AlertToast.git", branch: "master"),
//        .package(url: "https://github.com/lake-of-fire/swiftui-layout-guides.git", branch: "main"),
//        .package(url: "https://github.com/exyte/Grid.git", branch: "master"),
//        .package(url: "https://github.com/JiHoonAHN/XcodeSnippet.git", branch: "main"),
        .package(url: "https://github.com/lake-of-fire/StoreHelper.git", revision: "60b410573cc36d7da51c0548fdcae49619c30f03"),
        .package(url: "https://github.com/shaps80/SwiftUIBackports.git", revision: "2beebc6960375b3af3655447586e768a5271a5c2"),
//        .package(url: "https://github.com/ryanlintott/FrameUp.git", branch: "main"),
//        .package(url: "https://github.com/tevelee/SwiftUI-Flow.git", branch: "main"),
//        .package(path: "../SwiftUI-Flow"),
//        .package(url: "https://github.com/danielsaidi/SwiftUIKit.git", branch: "master"),
        .package(url: "https://github.com/lake-of-fire/FilePicker.git", revision: "4e445870eb07ae9c1e1aeedbb9b1098eaaabfb69"),
        .package(url: "https://github.com/weichsel/ZIPFoundation.git", branch: "development"),
        .package(url: "https://github.com/nicklockwood/LRUCache.git", from: "1.1.2"),
//        .package(url: "https://github.com/kean/Pulse.git", branch: "main"),
        .package(url: "https://github.com/stevengharris/SplitView.git", revision: "7737a80740919c2fa94a6e64f870d37ef77b9b5f"),
        .package(url: "https://github.com/lake-of-fire/VisionLiveText_SwiftUICompatible.git", revision: "4507047c5300582603c8e19040634bd86a534ab2"),
        .package(url: "https://github.com/EmergeTools/Pow.git", revision: "f650bd26c71084a49a99185f4b3e9c05a4a3ac8d"),
        .package(url: "https://github.com/apple/swift-log.git", revision: "d5dbc04d530c510eb4e9072c4958c511e612b2b1"),
        .package(url: "https://github.com/pointfreeco/sqlite-data.git", from: "1.4.1"),
        .package(url: "https://github.com/Tunous/DebouncedOnChange.git", revision: "2583a30a8d277c3475c1b3a10b0f902a7be34f3b"),
        .package(url: "https://github.com/lake-of-fire/Puppy.git", revision: "d193774c3a9b052d144ec86d4cca5b36442cdc5a"),
        .package(url: "https://github.com/lake-of-fire/CloudKitSyncMonitor.git", revision: "40176273ab7197e041e36d202ddd6385541ef46d"),
        .package(url: "https://github.com/johnpatrickmorgan/NavigationBackport.git", revision: "540d823fdfbbe495cbbe0afc80c409d63c9995c0"),
        //        .package(path: "../FramedScreenshotsTool"),
    ],
    targets: [
        // Targets are the basic building blocks of a package. A target can define a module or a test suite.
        // Targets can depend on other targets in this package, and on products in packages this package depends on.
        .target(
            name: "LakeKit",
            dependencies: [
                .product(name: "SwiftUIWebView", package: "swiftui-webview"),
//                .product(name: "RealmSwift", package: "RealmBinary"),
                .product(name: "RealmSwift", package: "realm-swift"),
                .product(name: "RealmSwiftGaps", package: "RealmSwiftGaps"),
                .product(name: "SQLiteData", package: "sqlite-data"),
                .product(name: "Popovers", package: "Popovers"),
                .product(name: "OrderedCollections", package: "swift-collections"),
                .product(name: "DebouncedOnChange", package: "DebouncedOnChange"),
                .product(name: "BetterSafariView", package: "BetterSafariView2"),
                .product(name: "KeychainSwift", package: "keychain-swift"),
                .product(name: "ZIPFoundation", package: "ZipFoundation"),
                .product(name: "DSFSearchField", package: "DSFSearchField"),
                .product(name: "BigSyncKit", package: "BigSyncKit"),
//                .product(name: "ExyteGrid", package: "Grid"),
//                .product(name: "XcodeSnippet", package: "XcodeSnippet"),
                .product(name: "StoreHelper", package: "StoreHelper"),
                .product(name: "SwiftUIBackports", package: "SwiftUIBackports"),
//                .product(name: "FrameUp", package: "FrameUp"),
//                .product(name: "Flow", package: "SwiftUI-Flow"),
                //                .product(name: "SwiftUIKit", package: "SwiftUIKit"),
                .product(name: "VisionLiveText_SwiftUICompatible", package: "VisionLiveText_SwiftUICompatible"),
                .product(name: "FilePicker", package: "FilePicker"),
                .product(name: "SwiftUIDownloads", package: "SwiftUIDownloads"),
                .product(name: "LRUCache", package: "LRUCache"),
//                .product(name: "Pulse", package: "Pulse"),
//                .product(name: "PulseUI", package: "Pulse"),
                .product(name: "SwiftUtilities", package: "SwiftUtilities"),
                .product(name: "SplitView", package: "SplitView"),
                .product(name: "LakeImage", package: "LakeImage"),
                .product(name: "Logging", package: "swift-log"),
                .product(name: "Puppy", package: "Puppy"),
                .product(name: "Pow", package: "Pow"),
//                .product(name: "Inferno", package: "Inferno"),
                .product(name: "CloudKitSyncMonitor", package: "CloudKitSyncMonitor"),
                .product(name: "NavigationBackport", package: "NavigationBackport"),
            ],
            resources: [
                .process("Resources"),
//                .copy("Resources/CSS/Reader.css"),
//                .process("Resources/CSS/"),
//                .process("Resources/JS/"),
//                .copy("Resources/JS/Readability/"),
//                .copy("Resources/CSS/manabi_panel.css"),
//                .copy("Resources/CSS/manabi_readability.css"),
//                .copy("Resources/JS/manabi_panel.js"),
//                .copy("Resources/JS/manabi_reader.js"),
//                .copy("Resources/JS/popper.min.js"),
//                .copy("Resources/JS/tippy_css_loader.js"),
//                .copy("Resources/JS/tippy.umd.min.js"),
            ],
            linkerSettings: [
//                .unsafeFlags(
//                    ["-Xlinker", "-interposable"],
//                    .when(configuration: .debug))
            ]
        ),
        .testTarget(
            name: "LakeKitTests",
            dependencies: ["LakeKit"]),
    ]
)
